<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style1.css">
    <title>La cuisine</title>
</head>
<body>
    <div id="all">

        <!-- Header -->

        <header>
            <div id="info">
                <span class="infop">+216 12 345 678</span>
                <span class="infop">phpteam@project.com</span>
                <span class="infop">Open hours: Monday - Sunday 8:00AM - 9:00PM</span>
            </div>
            <p>
                <span><b id="lb">L</b></span>a <span><b id="ly">c</b></span>uisine
            </p>
            <div id="startnow">
                <a href="#lcl" id="gs">Get your food now</a>
            </div>
        </header>

        <!-- menu -->

                <div id="navbar">
                    <a href="index1.php" class="menu" ><b id="lcl">La cuisine</b></a>
                    <a href="index1.php" class="menu">Home</a>
                    <!-- <a href="#tt" class="menu">Menu</a>
                    <a href="#" class="menu">Tendence</a> -->
                    <a href="contact.html" class="menu">Contact</a>
                    <a href="#" class="menu" ><span id="btab">Book a table</span></a>
                </div>
        <!-- section -->
            <section>
                <div id="contenu_public">
                    <div id="food">
                        <div id="food_title">
                            <h3>Our Menu</h3>
                        </div>
                        <div id="boxfood">
                            <div id="bf">
                                <b>Breakfast</b>
                                <div id="bfc">
                                    <a href="#d1" class="linkb1">
                                    <div class="box_fd">
                                        <p>
                                            <img class="imgf" src="image/breakfast-1.jpg" alt="" width="50%"><br>
                                            Beef with potatoes <br>
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u>                                       
                                    </p>                                       
                                    </div>
                                    </a>
                                    <a href="#d1" class="linkb1">
                                    <div class="box_fd">
                                        <p>
                                        <img class="imgf" src="image/breakfast-2.jpg" alt="" width="50%"><br>
                                        Beef with potatoes<br>
                                        Meat, Potatoes, Rice, Tomatoe<br>
                                        <u>$29</u>/p>
                                    </div>
                                    </a>
                                    <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                        <p>
                                            <img class="imgf" src="image/breakfast-3.jpg" alt="" width="50%"><br>
                                            Beef with potatoes<br> 
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u></p>
                                        </div>
                                    </a>
                                    </div>
                            </div>
                            <div id="lunch">
                                <b>Lunch</b>
                                <div id="lc">
                                        <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                            <p>
                                                    <img class="imgf" src="image/breakfast-4.jpg" alt="" width="50%"><br>
                                                Beef with potatoes <br> 
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u></p>                                            
                                        </div>
                                        </a>
                                        <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                            <p>
                                                    <img class="imgf" src="image/breakfast-5.jpg" alt="" width="50%"><br>
                                                Beef with potatoes<br> 
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u></p>
                                        </div>
                                        </a>
                                        <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                           <p>
                                                <img class="imgf" src="image/breakfast-6.jpg" alt="" width="50%"><br>
                                               Beef with potatoes<br>
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u></p>
                                        </div>
                                        </a>
                                </div>
                            </div>
                            <div id="dinner">
                                <b>Dinner</b>
                                <div id="dc">
                                        <a href="#d1" class="linkb1">
                                            <div class="box_fd" >
                                            <p>
                                                    <img class="imgf" src="image/breakfast-7.jpg" alt="" width="50%"><br>
                                                Beef with potatoes <br>
                                            Meat, Potatoes, Rice, Tomatoe <br>
                                            <u>$29</u></p>                                            
                                        </div>
                                        </a>
                                        <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                            <p>
                                                    <img class="imgf" src="image/breakfast-8.jpg" alt="" width="50%"><br>
                                                Beef with potatoes<br>
                                            Meat, Potatoes, Rice, Tomatoe<br>
                                            <u>$29</u></p>
                                        </div>
                                        </a>
                                        <a href="#d1" class="linkb1">
                                        <div class="box_fd">
                                           <p>
                                                    <img class="imgf" src="image/breakfast-9.jpg" alt="" width="50%"><br>
                                                Beef with potatoes <br> 
                                                Meat, Potatoes, Rice, Tomatoe <br>
                                                <u>$29</u></p>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="ci">
                        <div id="cibox">
                            <div id="cl">
                                <h3>-Login-</h3>
                            </div>
                            <div id="contenairec">
                            <form action="post">
                                    <table>
                                            <tr>
                                                <td>
                                                    <label for="mail">Mail </label>
                                                </td>
                                                <td>
                                                    <input type="text" placeholder="Tape your name" id="mail" name="mail" >
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <label for="pwd">Password </label>
                                                </td>
                                                <td>
                                                    <input type="password" placeholder="Your password" id="pwd" name="mail">
                                                </td>
                                            </tr>
                                            <td></td>
                                            <td>
                                            <input id="login_s" type="submit" name="login" value="Login">
                                            </td>
                                            
                                    </table>
                            </form>
                        </div>
                        <br>
                        or
                        <div id="contenairei">
                                <h2>-Sign in-</h2>
                                <form method="post" action="">
                                    <table>
                                        <tr>
                                            <td>
                                                <label for="user">User </label>
                                            </td>
                                            <td>
                                                <input type="text" placeholder="Your name" id="user" name="user">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label for="mail">Mail </label>
                                            </td>
                                            <td>
                                                <input type="mail" placeholder="Your mail" id="mail" name="mail">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label for="mail2">Confirm your mail </label>
                                            </td>
                                            <td>
                                                <input type="mail" placeholder="Confirm your mail" id="mail2" name="mail2">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label for="pw">Password </label>
                                            </td>
                                            <td>
                                                <input type="password" placeholder="Your password" id="pw" name="pw">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label for="pw2">Confirm your password </label>
                                            </td>
                                            <td>
                                                <input type="password" placeholder="Confirm your password" id="pw2" name="pw2">
                                            </td>
                                        </tr>
                                        <td></td>
                                        <td>
                                            <input type="submit" name="singin" value="Sign in">
                                        </td>
                                    </table>
                                </form>
                            </div>
                    </div>
                    </div>
                </div>
            </section>

            
            <!-- footer -->
            <footer>
                <div id="contact">
                        <div id="osm">
                            <div id="os">
                                <!-- Link Facebook -->
                                <!-- Link Instagram -->
                                <!-- Link Twiter -->
                            </div>
                        </div>
                        <div id="cp">
                            <p id="cont">Copyright ©2019 All rights reserved</p>
                        </div>
                </div>
            </footer>
</body>
</html> 